### ISSUE TITLE
report: Add design decision to have both identifiers and types as identifiers

### ISSUE THREAD

**Issue by sangisos** [mewmew/uc#24]

**Comment by sangisos** [comment]
Can't edit issue in mobile phone. Issue should read "Add design decision to have both identifiers and types as identifiers" and should be tagged report and assignment 1

**Comment by mewmew** [comment]
Perfect! Good that you managed to remember this design decision.

**Comment by mewmew** [comment]
Refer to issue #21 for the implementation.
