### ISSUE TITLE
semantic: FuncCall argument count and type not being checked against FuncType

### ISSUE THREAD

**Issue by sangisos** [mewmew/uc#56]
See files
[incorrect/semantic/se15.c](https://github.com/mewmew/uc/blob/master/testdata/incorrect/semantic/se15.c#L8)
[incorrect/semantic/se16.c](https://github.com/mewmew/uc/blob/master/testdata/incorrect/semantic/se16.c#L9)
[incorrect/semantic/se26.c](https://github.com/mewmew/uc/blob/master/testdata/incorrect/semantic/se26.c#L9)

**Comment by mewmew** [comment]
Implemented with commit fa67892390fb9fab3f46adedbb4a14ae140436f0 and 24fe82273517f1c4309e8eafb194224b244d8052.

**Comment by sangisos** [comment]
Updated 7 in commit fa67892

**Comment by mewmew** [comment]
> Updated 7 in commit fa67892

Already noted above :) "Implemented with commit fa67892 and 24fe822."
