### ISSUE TITLE
semantic: Cleanup and separation of concern

### ISSUE THREAD

**Issue by mewmew** [mewmew/uc#57]
The semantic analysis and type-checker packages are in need of love and could use a refactoring to clear up their separation of concern. Currently `semcheck.Check` is empty, and `typecheck.Check` does all the work, even pure semantic-checking. We should separate concern and clean up this part of the code.

**Comment by sangisos** [comment]
I agree.  Was trying to separate things, but didn't separate enough. Let's
go through this tomorrow.

Med Vänliga Hälsningar
Alexander Andersson

**Comment by mewmew** [comment]
When we do the cleanup (which may happen after v0.3) we should definitely address the issue of resolving identifiers of the universe scope. A temporary workaround was added with commit 12c9719a4ab781d7d315e3f0b5716d34609d1270.

**Comment by sangisos** [comment]
In the assignment it says

"Hints

You need to design data structures for the representation of the types of variables and functions."

Can we say this is fulfilled with the code in current state?

**Comment by mewmew** [comment]
> Can we say this is fulfilled with the code in current state?

Definitely, it is what the types package does.

**Comment by mewmew** [comment]
Initial cleanup in commit 25e4a3cf7a6a7fcd2b20181ddaa8c63b26ea1a7e. The few semantic checks which are still done by the type-checker will remain, as they improve error output. TODOs for pure semantic checks have been moved to the `semcheck` package.
